name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: |
          # build image

          docker build -t mustafa-test-blzor .
          #run image
          docker run -d \
           -p 9875:8080 \
           --name mustafa-test-blzor \
            mustafa-test-blzor

          echo "make it end"
      